apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: restapi-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: restapi
    kind: Deployment
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 70
