version: "3.7"
services:
  mongodb:
    container_name: mongo-dev
    image: mongo:4.2.12
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - '27017:27017'
    volumes:
      - /opt/docker/volumes/mongoDB:/data/db
    networks:
      - main-network
  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.54.0
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongo-dev
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    ports:
      - '8081:8081'
    networks:
      - main-network
  web:
    image: prgmw/restapi:latest
    container_name: restapi
    restart: on-failure
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=admin
      - SPRING_DATA_MONGODB_PASSWORD=pass
      - SPRING_DATA_MONGODB_DATABASE=admin
    networks:
      - main-network

networks:
  main-network:
    driver: bridge